### ISSUE TITLE
UMLS REST API wrapper

### ISSUE THREAD

**Issue by dermatologist** [dermatologist/umlsjs#8]
Help needed to complete wrappers for other endpoints on the [UMLS](https://www.nlm.nih.gov/research/umls/index.html) API. This should be relatively simple as the already implemented UMLSSearch can be a template. Ideal for nodejs beginner-medium level programmers.

**Comment by baspalinckx** [comment]
Would love to help out and give it a go!

**Comment by dermatologist** [comment]
> Would love to help out and give it a go!

Great @baspalinckx .
Thanks!

**Comment by baspalinckx** [comment]
I'm sorry @dermatologist, I'm afraid I don't get it. Could you be more specific what endpoints need work and what you mean by a wrapper?

**Comment by dermatologist** [comment]
Hi @baspalinckx

Sorry for the late reply. This makes calling [these API's](https://documentation.uts.nlm.nih.gov/rest/home.html) easy. Clicking on the endpoints listed there gives sample outputs. See the mocktest folder (fake-cui-response and mock.cuiSearch.spec.js).  Use *npm run mocktest* on develop branch (no key required). Any useful contribution will be accepted for hacktoberfest. 

Thanks again for checking this out!
Cheers.
